Tenir en compte DTCard en llegir l's23
gisce/primestg pull request #57
Opened 2020-11-26 13:27 UTC by xavitoro15

2020-11-26 14:17 UTC, davidmunoznovoa approved these changes

2020-12-24 12:31 UTC, tinogis requested changes

2020-12-24 12:31 UTC, tinogis commented on primestg/report/base.py
> +        if date_value.upper().startswith('FFFF') or e.get('DTCard') == 'Y':
* For **S23** `SpecialDays`, better do not use` _get_timestamp`
* Add some tests

2021-03-08 07:37 UTC, tinogis approved these changes

2021-03-08 07:42 UTC, merged